apiVersion: v1
kind: Pod
metadata:
  name: schema-registry
spec:
  containers:
    - name: schema-registry
#      image: confluentinc/cp-schema-registry:latest
      image: <image-name>
      ports:
        - containerPort: 8081
      env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: "schema-registry"
      resources:
        requests:
          memory: "2Gi"
        limits:
          memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service
spec:
  selector:
    app: schema-registry
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
